M48
; DRILL file {KiCad 7.0.5} date Sun Jun 11 14:57:03 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-11T14:57:03+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X190.0Y-65.0
X190.0Y-105.0
X240.0Y-65.0
X240.0Y-105.0
T0
M30
